---
# handlers file for install_httpd
- name: Enable port for httpd
  become_user: root
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Restart apache
  service:
    name: httpd
    state: restarted




