---
- name: Ensure semanage installed
  ansible.builtin.package:
    name: policycoreutils-python-utils
    state: present

- name: Config selinux
  ansible.builtin.seboolean:
    name: allow_ftpd_anon_write
    persistent: yes
    state: yes

- name: Config context resource
  ansible.builtin.sefcontext:
    target: /var/ftp/pub/upload
    setype: public_content_rw_t
    state: present
  notify: Restore context
